#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

echo "OPENSHIFT_INFINISPAN_HOST=${OPENSHIFT_GEAR_DNS}"
echo "OPENSHIFT_INFINISPAN_PORT=${OPENSHIFT_INFINISPAN_TCP_PROXY_PORT}"

